# Generated by Django 2.1.7 on 2019-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190225_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, help_text='jpg/png - file', null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
