# Generated by Django 2.1.7 on 2019-02-25 11:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190225_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
