# Generated by Django 2.1.7 on 2019-02-27 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190227_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 27, 19, 42, 25, 964447, tzinfo=utc)),
        ),
    ]
