# Generated by Django 2.1.7 on 2019-03-03 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20190227_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 3, 14, 15, 58, 330038, tzinfo=utc)),
        ),
    ]
